<?php

return 
[
    [
        'title' => 'Casa sul bel mare',
        'rooms' => 5,
        'beds' => 3,
        'bathrooms' => 1,
        'square_meters' => 70,
        // 'address' => 'Via Maratona, 9-11 00053 Civitavecchia RM',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'loft nel centro città',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 100,
        // 'address' => 'Via Spadari, 2, 20123 Milano MI',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'monolocale',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'square_meters' => 70,
        // 'address' => 'Via Gian Domenico Cassini, 19, 10129 Torino TO',
        'available' => 0,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'trilocale in periferia',
        'rooms' => 5,
        'beds' => 3,
        'bathrooms' => 2,
        'square_meters' => 120,
        // 'address' => 'Via Albano, 33, 00179 Roma RM',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'appartamento a due passi dall\'arno',
        'rooms' => 3,
        'beds' => 3,
        'bathrooms' => 1,
        'square_meters' => 90,
        // 'address' => 'Via del Franciabigio, 12, 50142 Firenze FI',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'bilocale luminoso',
        'rooms' => 3,
        'beds' => 1,
        'bathrooms' => 1,
        'square_meters' => 60,
        // 'address' => 'Salita Antonio Giusti, 1017, 16124 Genova GE',
        'available' => 0,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'monolocale per studenti',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'square_meters' => 60,
        // 'address' => 'Via Otto Colonne, 10, 40122 Bologna BO',
        'available' => 0,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'Baita sul Fiume',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 60,
        // 'address' => 'Via al Ponte, 1 46030 Borgo Virgilio MN',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'Cottage sul lago',
        'rooms' => 6,
        'beds' => 3,
        'bathrooms' => 2,
        'square_meters' => 90,
        // 'address' => 'Desenzano del Garda, 25015 Provincia di Brescia',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'Loft Bella Vita',
        'rooms' => 7,
        'beds' => 4,
        'bathrooms' => 2,
        'square_meters' => 120,
        // 'address' => 'Via Primo Cavallieri, 6, 16014 Campomorone GE',
        'available' => 0,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'Casa sul mare',
        'rooms' => 5,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 65,
        // 'address' => 'Viale Sas Linnas Siccas, 8-42, 08028 Sas Linnas Siccas NU',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
    [
        'title' => 'Casa sul mare',
        'rooms' => 5,
        'beds' => 2,
        'bathrooms' => 1,
        'square_meters' => 65,
        // 'address' => 'Viale Sas Linnas Siccas, 8-42, 08028 Sas Linnas Siccas NU',
        'available' => 1,
        'utilities' => [1],
        "user_id"       => "1",
        "image_id"   => "1",
        "message_id"  => "1",
        "address_id"   => "1",
        "view_id"     => "1",
        "sponsors" => [1],        
    ],
];