<?php

return 
[
    [
        'title'           => 'Casa sul bel mare',
        'rooms'           => 5,
        'beds'            => 3,
        'bathrooms'       => 1,
        'square_meters'   => 70,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'loft nel centro città',
        'rooms'           => 4,
        'beds'            => 2,
        'bathrooms'       => 1,
        'square_meters'   => 100,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'monolocale',
        'rooms'           => 2,
        'beds'            => 1,
        'bathrooms'       => 1,
        'square_meters'   => 70,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'trilocale in periferia',
        'rooms'           => 5,
        'beds'            => 3,
        'bathrooms'       => 2,
        'square_meters'   => 120,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'appartamento a due passi dall\'arno',
        'rooms'           => 3,
        'beds'            => 3,
        'bathrooms'       => 1,
        'square_meters'   => 90,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'bilocale luminoso',
        'rooms'           => 3,
        'beds'            => 1,
        'bathrooms'       => 1,
        'square_meters'   => 60,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'monolocale per studenti',
        'rooms'           => 2,
        'beds'            => 1,
        'bathrooms'       => 1,
        'square_meters'   => 60,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'Baita sul Fiume',
        'rooms'           => 4,
        'beds'            => 2,
        'bathrooms'       => 1,
        'square_meters'   => 60,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'Cottage sul lago',
        'rooms'           => 6,
        'beds'            => 3,
        'bathrooms'       => 2,
        'square_meters'   => 90,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'Loft Bella Vita',
        'rooms'           => 7,
        'beds'            => 4,
        'bathrooms'       => 2,
        'square_meters'   => 120,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'Casa in montagna',
        'rooms'           => 5,
        'beds'            => 2,
        'bathrooms'       => 1,
        'square_meters'   => 65,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
    [
        'title'           => 'Casa in campagna',
        'rooms'           => 5,
        'beds'            => 2,
        'bathrooms'       => 1,
        'square_meters'   => 65,
        'available'       => true,
        'utilities'       => [1],
        "user_id"         => "1",
        "sponsors"        => [1],        
    ],
];